name       : nim
version    : 0.17.2
release    : 11
source     :
    - https://nim-lang.org/download/nim-0.17.2.tar.xz : aaff1b5023fc4a5708f1d7d9fd8e2a29f1a7f58bf496532ff1e9d7e7c7ec82bd
license    : MIT
component  : programming
summary    : Nim programming language
description: |
    Nim is a statically typed, imperative programming language.
setup      : |
    %patch < $pkgfiles/0001-Change-to-correct-dirs.patch
    # fix some tests
    %patch -p1 < $pkgfiles/0003-fix-tasyncsend4757-test.patch
    %patch -p1 < $pkgfiles/0005-fix-tnewasyncudp-endianness.patch
    %patch -p1 < $pkgfiles/0007-fix-floats-in-tests.patch
builddeps  :
    - nodejs-devel # check
rundeps    :
    - glibc-devel
    - linux-headers
build      : |
    ./build.sh
    bin/nim c koch
    ./koch nimble
    ./koch tools
install    : |
    ./install.sh %installroot%

    install -Dm00755 bin/* $installdir/usr/bin
    install -Dm00644 tools/nim.bash-completion $installdir/usr/share/bash-completion/completions/nim
    install -Dm00644 dist/nimble/nimble.bash-completion $installdir/usr/share/bash-completion/completions/nimble
    mv $installdir%libdir%/nim/compiler.nimble $installdir%libdir%/nim/compiler/
check     : |
    # don't test everything because it's too long
    for cat in lib async float io bind rodfiles js debugger global threads
    do
        ./koch tests --pedantic category $cat -d:nimCoroutines || (echo "$cat test category failed" &&  exit 1)
    done
