name       : nim
version    : 1.4.0
release    : 17
source     :
    - https://nim-lang.org/download/nim-1.4.0.tar.xz : 9dfba2bed31a21a5a34231016dd556b1b5e0db23c01357cfab26aa8f27a6c23d
homepage   : https://nim-lang.org
license    : MIT
component  : programming
summary    : Nim programming language
description: |
    Nim is a statically typed, imperative programming language.
builddeps  :
    - nodejs-devel # check
rundeps    :
    - glibc-devel
    - linux-headers
setup      : |
    %patch -p1 < $pkgfiles/0001-Change-to-correct-dirs.patch
    %patch -p1 < $pkgfiles/0002-change-nim-gdb-shebang.patch
    %patch -p1 < $pkgfiles/Stateless.patch
build      : |
    ./build.sh
    bin/nim c koch
    ./koch boot -d:release
    ./koch tools -d:release
install    : |
    ./install.sh %installroot%
    install -dm00755 $installdir/usr/share/defaults/nim
    mv $installdir/etc/nim $installdir/usr/share/defaults
    rmdir $installdir/etc
    install -Dm00755 bin/* $installdir/usr/bin

    install -Dm00644 tools/nim.bash-completion $installdir/usr/share/bash-completion/completions/nim
    install -Dm00644 tools/nim.zsh-completion $installdir/usr/share/zsh/site-functions/_nim
    install -Dm00644 dist/nimble/nimble.bash-completion $installdir/usr/share/bash-completion/completions/nimble
    install -Dm00644 dist/nimble/nimble.zsh-completion $installdir/usr/share/zsh/site-functions/_nimble

    # Compiler directory should not be part of binary package according to https://nim-lang.github.io/Nim/packaging.html
    mv $installdir/%libdir%/nim/compiler.nimble $installdir/%libdir%/nim/compiler
    rm -r $installdir/%libdir%/nim/compiler

    # Remove doc directory.
    rm -r $installdir/usr/share/nim
check      : |
    # Don't test everything because it takes too long.
    export PATH=$workdir/bin:$PATH
    for cat in lib async float io bind rodfiles js debugger global threads
    do
        ./koch tests --pedantic category $cat -d:nimCoroutines || (echo "$cat test category failed" &&  exit 1)
    done
