name       : nim
version    : 0.13.0
release    : 2
source     :
    - http://nim-lang.org/download/nim-0.13.0.tar.xz : 688da1487eb507e0aa96b757a2a4a311123ad38ab68a10277a0415724f982b33
license    : MIT
summary    : Nim programming language
description: |
    Nim is a statically typed, imperative programming language.
setup      : |
    %patch < $pkgfiles/mimic-install.patch
build      : |
    ./build.sh
install    : |
    ./install.sh %installroot%
