name       : nim
version    : 0.15.0
release    : 5
source     :
    - http://nim-lang.org/download/nim-0.15.0.tar.xz : c514535050b2b2156147bbe6e23aafe07cd996b2afa2c81fa9a09e1cd8c669fb
license    : MIT
component  : programming
summary    : Nim programming language
description: |
    Nim is a statically typed, imperative programming language.
setup      : |
    %patch < $pkgfiles/0001-Change-to-correct-dirs.patch
build      : |
    ./build.sh
install    : |
    ./install.sh %installroot%
