name       : nim
version    : 0.17.0
release    : 10
source     :
    - https://nim-lang.org/download/nim-0.17.0.tar.xz : 36e18dd9384f6c67e6d0199b871b43e774a0af30532698184d6f5a9cc9ac7a9b
license    : MIT
component  : programming
summary    : Nim programming language
description: |
    Nim is a statically typed, imperative programming language.
setup      : |
    %patch < $pkgfiles/0001-Change-to-correct-dirs.patch
build      : |
    ./build.sh
    bin/nim c koch
    ./koch nimble
install    : |
    ./install.sh %installroot%
    install -Dm00755 bin/nimble $installdir/usr/bin/nimble
    mv $installdir%libdir%/nim/compiler.nimble $installdir%libdir%/nim/compiler/
