name       : nim
version    : 0.14.2
release    : 4
source     :
    - http://nim-lang.org/download/nim-0.14.2.tar.xz : 8f8d38d70ed57164795fc55e19de4c11488fcd31dbe42094e44a92a23e3f5e92
license    : MIT
component  : programming
summary    : Nim programming language
description: |
    Nim is a statically typed, imperative programming language.
setup      : |
    %patch < $pkgfiles/0001-Change-to-correct-dirs.patch
build      : |
    ./build.sh
install    : |
    ./install.sh %installroot%
