name       : nim
version    : 0.16.0
release    : 8
source     :
    - http://nim-lang.org/download/nim-0.16.0.tar.xz : 9e199823be47cba55e62dd6982f02cf0aad732f369799fec42a4d8c2265c5167
license    : MIT
component  : programming
summary    : Nim programming language
description: |
    Nim is a statically typed, imperative programming language.
setup      : |
    %patch < $pkgfiles/0001-Change-to-correct-dirs.patch
build      : |
    ./build.sh
    bin/nim c koch
    ./koch nimble
install    : |
    ./install.sh %installroot%
    install -Dm00755 bin/nimble $installdir/usr/bin/nimble
