name       : nim
version    : 0.12.0
release    : 1
source     :
    - http://nim-lang.org/download/nim-0.12.0.tar.xz : 0fb860137f0888f6b1a593d9b115fd7057983b7355f4f9922bb82a49ac875235
license    : MIT
summary    : Nim programming language
description: |
    Nim is a statically typed, imperative programming language.
setup      : |
    %patch < $pkgfiles/mimic-install.patch
build      : |
    ./build.sh
install    : |
    ./install.sh %installroot%
