name       : nim
version    : 0.14.0
release    : 3
source     :
    - http://nim-lang.org/download/nim-0.14.0.tar.xz : 023524b422c745a8fc2ee1207e35babbeb9c6b5f81a3bf85071986b48debd6a5
license    : MIT
component  : programming
summary    : Nim programming language
description: |
    Nim is a statically typed, imperative programming language.
setup      : |
    %patch < $pkgfiles/0001-Change-to-correct-dirs.patch
build      : |
    ./build.sh
install    : |
    ./install.sh %installroot%
